ch1/information/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.information, name='information')
]

ch1/mysite/urls.py
from django.contrib import admin
from django.urls import re_path, include
from . import views

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    re_path(r'^$', views.main, name='main'),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^theme/', include(('theme.urls', 'theme'), namespace='theme')),
    re_path(r'^information/', include(('information.urls', 'information'), namespace='information'))
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ch1/theme/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.theme, name='theme'),
    re_path(r'^info/$', views.theme_info, name='theme_info'),
    re_path(r'^(?P<date>(19|20)\d{2}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[0-1]))/$',
            views.theme_list, name='theme_list'),
    re_path(r'^(?P<date>(19|20)\d{2}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[0-1]))/(?P<theme>[\w|\W]+)/'
            r'(?P<time>[\w|\W]+)/complete/$', views.booking_complete, name='booking_complete'),
    re_path(r'^(?P<date>(19|20)\d{2}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[0-1]))/(?P<theme>[\w|\W]+)/'
            r'(?P<time>[\w|\W]+)/$', views.booking_detail, name='booking_detail'),
    re_path(r'^(?P<date>(19|20)\d{2}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[0-1]))/(?P<theme>[\w|\W]+)/$',
            views.theme_booking, name='theme_booking'),
]

ch1/mysite/views.py
from django.shortcuts import render
import datetime
import sys
sys.path.append('..')
from information.models import Information
from theme.models import Theme



def main(request):
    theme = Theme.objects.all()
    info = Information.objects.all()
    now = datetime.datetime.now()
    nowDate = now.strftime('%Y-%m-%d')
    print(nowDate)
    return render(request, 'main.html', {
        'today': nowDate,
        'info': info,
        'theme': theme,
    })

ch1/mysite/templates/base.html
<!DOCTYPE html>
<html lang="ko-kr">
    <head>
        <meta charset="utf-8">
        <!-- 부트스트랩 모바일 -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- 부트스트랩 -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script>
            $(window).scroll(function() {
                var scroll = $(window).scrollTop();

                if (scroll >= 100) {
                    $(".top-nav").addClass("light-header");
                } else {
                    $(".top-nav").removeClass("light-header");
                }
            });
        </script>
    </head>
    <body>
    {% load static %}
    {% for i in info %}
        <!-- PC 버전 -->
        <div class="d-none d-sm-block">
            <nav class="px-5 navbar navbar-expand-md top-nav" style="background-color:rgb(51,51,51);">
                <a class="navbar-brand" href="{% url 'main' %}">
                    <img width="160px" src="{{ i.logo.url }}">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"><i class="fa fa-bars" aria-hidden="true"></i></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link text-white font-weight-bold mx-2" href="{% url 'information:information' %}">이용안내<span class="sr-only"></span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white font-weight-bold mx-2" href="{% url 'theme:theme_info' %}">테마</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white font-weight-bold mx-2" href="{% url 'theme:theme_list' today %}">예약하기</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white font-weight-bold mx-2" href="">FAQ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white font-weight-bold mx-2" href="">Q&A</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white font-weight-bold mx-2" href="">예약확인 및 취소</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>

        <!-- 모바일 버전 -->
        <div class="p-2 d-block d-sm-none" style="background-color:rgb(51,51,51);">
            <div class="row text-center mb-3">
                <a class=text-center" href="{% url 'main' %}">
                    <img width="30%" src="{{ i.logo.url }}">
                </a>
            </div>
            <div class="row my-1" style="font-size:0.4rem">
                <div class="p-0 text-center col-2">
                    <a class="m-0 p-0 nav-link text-white font-weight-bold mx-2" href="{% url 'information:information' %}">이용안내<span class="sr-only"></span></a>
                </div>
                <div class="p-0 text-center col-2">
                    <a class="m-0 p-0 nav-link text-white font-weight-bold mx-2" href="{% url 'theme:theme_info' %}">테마</a>
                </div>
                <div class="p-0 text-center col-2" >
                    <a class="m-0 p-0 nav-link text-white font-weight-bold mx-2" href="{% url 'theme:theme_list' today %}">예약하기 </a>
                </div>
                <div class="p-0 text-center col-2" >
                    <a class="m-0 p-0 nav-link text-white font-weight-bold mx-2" href="">FAQ</a>
                </div>
                <div class="p-0 text-center col-2">
                    <a class="m-0 p-0 nav-link text-white font-weight-bold mx-2" href="">Q&A</a>
                </div>
                <div class="p-0 text-center col-2">
                    <a class="m-0 p-0 nav-link text-white font-weight-bold mx-2" href="">확인/취소</a>
                </div>
            </div>
        </div>

        {% block content %}

        {% endblock %}

    <!-- 푸터 -->
    <!-- PC 버전 -->
        <footer class="py-4 px-5 d-none d-sm-block" style="background-color:rgb(51,51,51);">
            <div class="px-4">
                <h6 class="text-white" style="font-size:13pt">TEL : {{ i.Tel }} /  영업시간 : {{ i.businessHours }}</h6>
                <p style="font-size:11pt" class="text-white">상호명 : {{ i.fullName }} /  대표자 : {{ i.CEO }} /  사업자등록번호 : {{ i.businessLicense }} /  주소 : {{ i.address }} /  E-mail : {{ i.Email }}</p>
                <p class="text-center text-white mt-2" style="margin-bottom:0">Copyrightⓒ 2019 Bizchool. All right reserved.</p>
            </div>
        </footer>

    <!-- 모바일 버전 -->
        <footer class="py-3 d-block d-sm-none" style="background-color:rgb(51,51,51);">
            <p style="font-size:0.8rem" class="text-white text-center">
                <b style="font-size:1.1rem">STORE INFO.</b><br>
                <b style="font-size:1.8rem"><a style="color:yellow;text-decoration:none;" href="tel: 031-613-9788" class="tel">{{ i.Tel }}<br>
                </a></b>
                <span>번호 클릭 시 전화 연결됩니다.</span><br /><br />
                <span style="font-size:1.2rem">계좌이체<br />
                    {{ i.bank }}</span><br />
                <br />
                상호명 : {{ i.fullName }} / 대표자 : {{ i.CEO }}<br />
                사업자등록번호 : {{ i.businessLicense }} <br />
                <div class="container">
                    <p style="font-size:0.8rem" class="text-white text-center">주소 : {{ i.address }}</p>
                </div>
            </p>
            <p class="text-center text-white mt-2" style="font-size:0.7rem;margin-bottom:0">Copyrightⓒ 2019 Bizchool. All right reserved.</p>
        </footer>
    {% endfor %}
    </body>