ch1/mysite/urls.py
from django.contrib import admin
from django.urls import re_path, include
from . import views

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    re_path(r'^$', views.main, name='main'),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^theme/', include(('theme.urls', 'theme'), namespace='theme')),
    re_path(r'^information/', include(('information.urls', 'information'), namespace='information'))
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ch1/theme/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.theme, name='theme'),
    re_path(r'^info/$', views.theme_info, name='theme_info'),
    re_path(r'^(?P<date>(19|20)\d{2}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[0-1]))/$',
            views.theme_list, name='theme_list'),
    re_path(r'^(?P<date>(19|20)\d{2}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[0-1]))/(?P<theme>[\w|\W]+)/'
            r'(?P<time>[\w|\W]+)/complete/$', views.booking_complete, name='booking_complete'),
    re_path(r'^(?P<date>(19|20)\d{2}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[0-1]))/(?P<theme>[\w|\W]+)/'
            r'(?P<time>[\w|\W]+)/$', views.booking_detail, name='booking_detail'),
    re_path(r'^(?P<date>(19|20)\d{2}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[0-1]))/(?P<theme>[\w|\W]+)/$',
            views.theme_booking, name='theme_booking'),
]

ch1/theme/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.shortcuts import reverse

class Theme(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='theme/')
    summary = models.TextField()
    numPeople = models.IntegerField(null=True, blank=True)
    difficulty = models.IntegerField()
    activity = models.IntegerField(null=True, blank=True)
    genre = models.CharField(max_length=20, null=True, blank=True)
    horror = models.IntegerField(null=True, blank=True)
    time1 = models.CharField(max_length=10)
    time2 = models.CharField(max_length=10)
    time3 = models.CharField(max_length=10)
    time4 = models.CharField(max_length=10)
    time5 = models.CharField(max_length=10)
    time6 = models.CharField(max_length=10)
    time7 = models.CharField(max_length=10)
    time8 = models.CharField(max_length=10)
    time9 = models.CharField(max_length=10)
    time10 = models.CharField(max_length=10)

    def __str__(self):
        return self.name


Way = (
    ('현장결제', '현장결제'),
    ('무통장선결제', '무통장선결제'),
)

Num = (
    ('1명', '1명'),
    ('2명', '2명'),
    ('3명', '3명'),
    ('4명', '4명'),
    ('5명', '5명'),
    ('6명', '6명'),
)


class Booking(models.Model):
    theme = models.ForeignKey(Theme, on_delete=models.CASCADE)
    date = models.DateField()
    time = models.CharField(max_length=20)
    name = models.CharField(max_length=10)
    phone = models.CharField(max_length=11)
    numPeople = models.CharField(max_length=20, choices=Num)
    depositWay = models.CharField(max_length=20, choices=Way)

    def get_absolute_url(self):
        return reverse('theme:booking_complete', args=[self.date, self.theme, self.time])

ch1/theme/forms.py
from django import forms
from .models import Booking


class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = [
            'name',
            'phone',
            'numPeople',
            'depositWay',
        ]
        widgets = {
            'name':forms.TextInput(
                attrs={
                    'style': 'width:100%',
                    'class': 'form-control',
                }
            ),
            'phone': forms.TextInput(
                attrs={
                    'style': 'width:100%',
                    'class': 'form-control',
                }
            ),
            'numPeople': forms.Select(
                attrs={
                    'style': 'width:100%',
                    'class': 'form-control',
                    'onchange': 'price_change();',
                    'name': 'numPeople'
                }
            ),
            'depositWay': forms.Select(
                attrs={
                    'style': 'width:100%',
                    'class': 'form-control',
                }
            )
        }

ch1/theme/views.py
from django.shortcuts import render, get_object_or_404, redirect
import datetime
from .models import Theme, Booking
from .forms import BookingForm
import sys
sys.path.append('..')
from information.models import Information


def theme(request):
    return render(request, 'theme/theme.html')


def theme_info(request):
    info = Information.objects.all()
    theme = Theme.objects.all()
    now = datetime.datetime.now()
    nowDate = now.strftime('%Y-%m-%d')
    return render(request, 'theme/theme_info.html', {
        'today': nowDate,
        'theme': theme,
        'info': info
    })


def theme_list(request, date):
    date = date
    year = date.split('-')[0]
    month = str(int(date.split('-')[1])-1)
    day = date.split('-')[2]
    booking = Booking.objects.all()
    booking = booking.filter(date=date)
    info = Information.objects.all()
    theme = Theme.objects.all()
    now = datetime.datetime.now()
    nowDate = now.strftime('%Y-%m-%d')
    return render(request, 'theme/theme_list.html', {
        'date': date,
        'year': year,
        'month': month,
        'day': day,
        'booking': booking,
        'today': nowDate,
        'theme': theme,
        'info': info,
    })


def theme_booking(request, date, theme):
    date = date
    year = int(date.split('-')[0])
    month = int(date.split('-')[1]) - 1
    day = int(date.split('-')[2])
    themes = Theme.objects.all()
    info = Information.objects.all()
    theme = get_object_or_404(Theme, name=theme)
    booking = Booking.objects.all()
    booking = booking.filter(date=date, theme=theme)
    time1_hour = int(theme.time1.split(':')[0])
    time1_min = int(theme.time1.split(':')[1])
    time2_hour = int(theme.time2.split(':')[0])
    time2_min = int(theme.time2.split(':')[1])
    time3_hour = int(theme.time3.split(':')[0])
    time3_min = int(theme.time3.split(':')[1])
    time4_hour = int(theme.time4.split(':')[0])
    time4_min = int(theme.time4.split(':')[1])
    time5_hour = int(theme.time5.split(':')[0])
    time5_min = int(theme.time5.split(':')[1])
    time6_hour = int(theme.time6.split(':')[0])
    time6_min = int(theme.time6.split(':')[1])
    time7_hour = int(theme.time7.split(':')[0])
    time7_min = int(theme.time7.split(':')[1])
    time8_hour = int(theme.time8.split(':')[0])
    time8_min = int(theme.time8.split(':')[1])
    time9_hour = int(theme.time9.split(':')[0])
    time9_min = int(theme.time9.split(':')[1])
    time10_hour = int(theme.time10.split(':')[0])
    time10_min = int(theme.time10.split(':')[1])
    now = datetime.datetime.now()
    nowDate = now.strftime('%Y-%m-%d')
    date = date
    return render(request, 'theme/theme_booking.html', {
        'date': date,
        'year': year,
        'month': month,
        'day': day,
        'themes': themes,
        'theme': theme,
        'today': nowDate,
        'info': info,
        'booking': booking,
        'time1_hour': time1_hour,
        'time1_min': time1_min,
        'time2_hour': time2_hour,
        'time2_min': time2_min,
        'time3_hour': time3_hour,
        'time3_min': time3_min,
        'time4_hour': time4_hour,
        'time4_min': time4_min,
        'time5_hour': time5_hour,
        'time5_min': time5_min,
        'time6_hour': time6_hour,
        'time6_min': time6_min,
        'time7_hour': time7_hour,
        'time7_min': time7_min,
        'time8_hour': time8_hour,
        'time8_min': time8_min,
        'time9_hour': time9_hour,
        'time9_min': time9_min,
        'time10_hour': time10_hour,
        'time10_min': time10_min,
    })


def booking_detail(request, date, theme, time):
    time = time
    date = date
    info = Information.objects.all()
    theme = get_object_or_404(Theme, name=theme)
    now = datetime.datetime.now()
    nowDate = now.strftime('%Y-%m-%d')
    if request.method == 'POST':
        form = BookingForm(request.POST, request.FILES)
        if form.is_valid():
            booking = form.save(commit=False)
            booking.theme = theme
            booking.date = date
            booking.time = time
            booking.save()
            return redirect(booking)
    else:
        form = BookingForm()

    return render(request, 'theme/booking_detail.html', {
        'theme': theme,
        'date': date,
        'time': time,
        'today': nowDate,
        'info': info,
        'form': form,
    })


def booking_complete(request, date, theme, time):
    info = Information.objects.all()
    now = datetime.datetime.now()
    nowDate = now.strftime('%Y-%m-%d')
    return render(request, 'theme/booking_complete.html', {
        'today': nowDate,
        'info': info,
    })

ch1/theme/templates/theme/booking_complete.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid py-5" style="background-color:black">
    <h1 class="text-center text-white">BOOKING</h1>
    <h4 class="text-center pb-4" style="color:rgb(171,171,171);">예약 완료</h4>
    <div class="container">
        <div class="container">
            <div class="row my-3">
                <div class="col-2"></div>
                <div class="col-8">
                    <div class="row">
                        <div class="col-4">
                            <h4 class="text-white text-center">0<span style="color:rgb(232,102,52);">1</span>. 날짜/룸 선택</h4>
                        </div>
                        <div class="col-4">
                            <h4 class=" text-white text-center">0<span style="color:rgb(232,102,52);">2</span>. 예약정보 입력</h4>
                        </div>
                        <div class="col-4">
                            <h4 class="pb-3 text-center text-white" style="border-bottom:3px solid white">0<span style="color:rgb(232,102,52);">3</span>. 예약 완료</h4>
                        </div>
                    </div>
                </div>
                <div class="col-2"></div>
            </div>
            <div class="row my-3 py-4">
                <div class="col-2"></div>
                <div class="text-center col-8 py-5 my-4" style="border:3px solid white;">
                    <div class="py-4">
                        <h5 class="text-center text-white">신청하신 테마방 예약이 완료되었습니다.</h5>
                        <h5 class="text-center text-white">예약 결과는 문자로 발송됩니다.</h5>
                        <h5 class="text-center text-white">[ 예약 완료 ]</h5>
                    </div>
                </div>
                <div class="col-2"></div>
            </div>
        </div>
    </div>
</div>



{% endblock %}

ch1/theme/templates/theme/booking_detail.html
{% extends 'base.html' %}

{% block content %}

<script>
    function price_change(){
        var form = document.BookingForm;
        if (form.numPeople.options[form.numPeople.selectedIndex].value == "1명"){
            {% for i in info %}
            Price.innerHTML = "금액 : " + MoneySwap({{ i.people1 }}, 1) + "원";
            {% endfor %}
            return;
        }
        if (form.numPeople.options[form.numPeople.selectedIndex].value == "2명"){
            {% for i in info %}
            Price.innerHTML = "금액 : " + MoneySwap({{ i.people2 }}, 2) + "원";
            {% endfor %}
            return;
        }
        if (form.numPeople.options[form.numPeople.selectedIndex].value == "3명"){
            {% for i in info %}
            Price.innerHTML = "금액 : " + MoneySwap({{ i.people3 }}, 3) + "원";
            {% endfor %}
            return;
        }
        if (form.numPeople.options[form.numPeople.selectedIndex].value == "4명"){
            {% for i in info %}
            Price.innerHTML = "금액 : " + MoneySwap({{ i.people4 }}, 4) + "원";
            {% endfor %}
            return;
        }
        if (form.numPeople.options[form.numPeople.selectedIndex].value == "5명"){
            {% for i in info %}
            Price.innerHTML = "금액 : " + MoneySwap({{ i.people5 }}, 5) + "원";
            {% endfor %}
            return;
        }
        if (form.numPeople.options[form.numPeople.selectedIndex].value == "6명"){
            {% for i in info %}
            Price.innerHTML = "금액 : " + MoneySwap({{ i.people6 }}, 6) + "원";
            {% endfor %}
            return;
        }
    }
    function MoneySwap(mValue, num){
       var price = num * mValue;
       var temp_str = String(price);
       for(var i = 0 , retValue = String() , stop = temp_str.length; i < stop ; i++) {
        retValue = ((i%3) == 0) && i != 0 ? temp_str.charAt((stop - i) -1) + "," + retValue : temp_str.charAt((stop - i) -1) + retValue;
       }
       return retValue;
    }

</script>

{{ form.media }}
<form name="BookingForm" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="container-fluid py-5 px-5" style="background-color:black">
        <h1 class="text-center text-white">BOOKING</h1>
        <h4 class="text-center pb-5" style="color:rgb(171,171,171);">예약정보 입력</h4>
        <div class="container px-5">
            <div clas="container px-5">
                <div class="container px-5">
                    <hr class="mx-5" style="border:1px solid white">
                    <div class="mx-5 px-4">
                        <table class="text-white table">
                            <tr style="border-color:black">
                                <th style="border-color:black" scope="row"><h4>예약일</h4></th>
                                <td style="border-color:black">{{ date }}</td>
                            </tr>
                            <tr style="border-color:black">
                                <th style="border-color:black" scope="row"><h4>시간</h4></th>
                                <td style="border-color:black">{{ time }}</td>
                                <td style="border-color:black"></td>
                                <td style="border-color:black"></td>
                                <td style="border-color:black"></td>
                                <td style="border-color:black"></td>
                                <td style="border-color:black"></td>
                                <td style="border-color:black"></td>
                            </tr>
                            <tr style="border-color:black">
                                <th style="border-color:black" scope="row"><h4>테마명</h4></th>
                                <td style="border-color:black">{{ theme.name }}</td>
                                <td style="border-color:black"></td>
                                <td style="border-color:black"></td>
                                <td style="border-color:black"></td>
                                <td style="border-color:black"></td>
                                <td style="border-color:black"></td>
                                <td style="border-color:black"></td>
                            </tr>
                            <tr style="border-color:black">
                                <th style="border-color:black" scope="row"><h4>예약자</h4></th>
                                <td style="border-color:black">{{ form.name }}</td>
                                <td style="border-color:black"></td>
                                <td style="border-color:black"></td>
                                <td style="border-color:black"></td>
                                <td style="border-color:black"></td>
                                <td style="border-color:black"></td>
                                <td style="border-color:black"></td>
                            </tr>
                            <tr style="border-color:black">
                                <th style="border-color:black" scope="row"><h4>연락처</h4></th>
                                <td style="border-color:black">{{ form.phone }}</td>
                                <td style="border-color:black"></td>
                                <td style="border-color:black"></td>
                                <td style="border-color:black"></td>
                                <td style="border-color:black"></td>
                                <td style="border-color:black"></td>
                                <td style="border-color:black"></td>
                            </tr>
                            <tr style="border-color:black">
                                <th style="border-color:black" scope="row"><h4>인원</h4></th>
                                <td style="border-color:black">{{ form.numPeople }}</td>
                                <td style="border-color:black"></td>
                                <td style="border-color:black"></td>
                                <td style="border-color:black"></td>
                                <td style="border-color:black"></td>
                                <td style="border-color:black"></td>
                                <td style="border-color:black"></td>
                            </tr>
                            <tr style="border-color:black">
                                <th style="border-color:black" scope="row"><h4>가격</h4></th>
                                <td style="border-color:black"><span id="Price">금액 : 40,000 원</span></td>
                            </tr>
                            <tr style="border-color:black">
                                <th style="border-color:black" scope="row"><h4>입금정보</h4></th>
                                {% for i in info %}
                                <td style="border-color:black">{{ i.bank }}</td>
                                {% endfor %}
                            </tr>
                            <tr style="border-color:black">
                                <th style="border-color:black" scope="row"><h4>예약방식</h4></th>
                                <td style="border-color:black">{{ form.depositWay }}</td>
                            </tr>
                        </table>
                    </div>
                </div>
                <input class="btn btn-primary text-center" type="submit" value="완 료">
            </div>
        </div>
    </div>
</form>


{% endblock %}

ch1/theme/templates/theme/theme.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        <title>Title</title>
</head>
<body>

</body>
</html>

ch1/theme/templates/theme/theme_info.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div class="container-fluid py-3" style="background-color:black">
    <!-- PC 버전 -->
    <div class="d-none d-sm-block">
        <h1 class="text-center text-white mt-4">ROOM</h1>
        <h4 class="text-center pb-4" style="color:rgb(171,171,171);">테마 소개</h4>
        <div class="container">
            <div class="container">
                <div class="container px-3">
                    {% for i in theme %}
                    <div class="row mx-4 my-4 px-2" style="background-color:rgb(51,51,51);">
                        <div class="col-5 text-center">
                            <img class="px-5 py-5" width="100%" src="{{ i.image.url }}">
                        </div>
                        <div class="col-7">
                            <div class="my-3">
                                <span class="font-weight-bold" style="color: rgb(241, 211, 92);font-size:27pt">{{ i.name }}</span>
                                <span class="text-white font-weight-bold" style="font-size:15pt;">&nbsp;&nbsp;({{ i.genre }})</span>
                            </div>
                            <h5 class="text-white">진행시간 : 60분    참여인원 : {{ i.numPeople }}   난이도: ★★★★☆☆</h5>
                            <br>
                            <p class="text-white mr-3" style="height:220px;">{{ i.summary|safe }}
                            </p>
                            <div class="d-flex justify-content-end px-5">
                                <a href="{% url 'theme:theme_booking' today i.name %}" style="text-decoration:none;">
                                    <div class="flex-sm-3 p-4" style="border: 2px solid white">
                                        <h5 class="text-white" style="margin:0">BOOKING</h5>
                                    </div>
                                </a>
                            </div>
                       </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <!-- PC 버전 끝 -->
    <!-- 모바일 버전 -->
    <div class="d-block d-sm-none mx-3">
        <h4 class="text-center text-white">ROOM</h4>
        <h5 class="text-center" style="color:rgb(171,171,171);">테마 소개</h5>
        {% for i in theme %}
        <div class="row my-4">
            <div class="col-lg-2"></div>
            <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12 py-3" style="background-color:rgb(51,51,51);">
                <h5 class="font-weight-bold text-center" style="color: rgb(241, 211, 92);font-size:27pt">{{ i.name }}</h5>
                <h6 class="text-white font-weight-bold text-center" style="font-size:15pt;">({{ i.genre }})</h6>
                <div class="row">
                    <div class="col-md-5 col-xs-12 text-center my-2">
                        <img width="100%" src="{{ i.image.url }}">
                    </div>
                    <div class="col-md-7">
                        <h5 class="text-white text-center">진행시간 : 60분&nbsp;&nbsp;&nbsp; 참여인원 : {{ i.numPeople }}</h5>
                        <h5 class="text-white text-center">난이도: ★★★★☆☆</h5>
                        <p class="text-white">{{ i.summary|safe }}</p>
                        <a class="text-center" href="{% url 'theme:theme_booking' today i.name %}" style="text-decoration:none;">
                            <div class="col-md-4 col-sm-4 col-xs-12 px-5 py-4" style="border: 2px solid white">
                                <p style="margin:0" class="text-white text-center">BOOKING</p>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2"></div>
        </div>
    {% endfor %}
    </div>
    <!-- 모바일 버전 끝 -->
</div>




{% endblock %}